version: "3"

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e_commerce
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  symfony:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/e_commerce?serverVersion=16&charset=utf8

volumes:
  database_data:
