version: "3"

services:
  web:
    build: .
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    restart: always

  database:
    image: postgres:latest
    container_name: symfony_database
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - database:/var/lib/postgresql/data:rw
    restart: always

volumes:
  database:
