version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16-alpine
    # ports:
    #   - "5000:5432"
    # env_file:
    #   - ./.env.data
    environment:
      POSTGRES_DB: e_commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    restart: always
  ###< doctrine/doctrine-bundle ###

  app:
    image: e-commerce-server:latest
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/e_commerce?serverVersion=16&charset=utf8
    depends_on:
      - database

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
